---
title: "Introduction to R for data analysis"
author: Peter Carbonetto
output:
  beamer_presentation:
    template: beamer.tex
    keep_tex: false
---

```{r knitr-options, echo=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,fig.align = "center",
                      results = "hide", fig.show = "hide", message = FALSE,
		      warning = FALSE)
```

Aims of workshop
================

*Add workshop aims here.*

Project: analyze 2016 & 2017 Divvy data
=======================================

*Describe the Divvy data analysis project and aims.*

It's your choice
================

Your may choose to...

+ Use R on your laptop.

+ Use RStudio on your laptop.

+ Use R or RStudio (Desktop or Server) on the RCC cluster.

+ Pair up with your neighbour.

+ Follow what I do on the projector.

*I can't guarantee that all examples will work exactly the same on
your laptop.*

Software we will use today
==========================

1. R

2. R packages `data.table` and `ggplot2`.

3. *RStudio is not optional.*

Outline of workshop
===================

*Add outline here.*

Download or "clone" git repository
==================================

The first step is to download the workshop packet to your computer
or the RCC cluster. Go to:

+ [github.com/rcc-uchicago/r-intro-divvy-2][github-repo]

To download, click green **Clone or download** button.

Or, if you have git, you can run this command:

```{bash download-repo, eval=FALSE}
git clone https://github.com/rcc-uchicago/
  R-intro-divvy-2.git
```

(Note the URL in the git command should not have contain any spaces.)

[github-repo]: https://github.com/rcc-uchicago/r-intro-divvy-2
